baseURL = "https://blog-ya3i.onrender.com/"
languageCode = "en-us"
title = "Leela Vadlamudi"
theme = "devise"
copyright = " "

# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 100
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/post/"
    weight = 10

# Configuration Features
[params]
  header_title = "Leela Vadlamudi"                 # Head title
  header_subtitle = " "
  home_image = "/images/avatar.png"          # Path to header image starting from the static directory
  recent_posts = 5                           # Max amount of recent posts to show
  mainSections = ["posts", "post", "blog"]   # Main sections to include in recent posts
  [[params.social]]
    fa_icon = "fab fa-github fa-2x"          # Font Awesome icon class
    href = "http://github.com/leela"      # Link to associate with icon (http://, https://, mailto:)
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-2x"
    href = "https://www.linkedin.com/in/leelavadlamudi/"
